### ISSUE TITLE
Validator error messages are misleading or confusing.

### ISSUE THREAD

**Issue by devjack** [Mermade/swagger2openapi#24]
Schema validation displays "expected $ref" instead of more helpful "Unexpected field `foo` expected a $ref or Schema."

### Checklist

- [ ] Validation: I believe my source definition is invalid OpenAPI 3.0.x but the validator does not complain

_Or rather, "I thought my definition was valid and the error message was unhelpful"._

### Detailed Description
openapi.yml:
```
...
components:
    schemas:
        SomeObject:
            $ref: 'resources/myobject.yml#/resource/SomeObject'
...
```

resources/myobject.yml
```
resource:
    SomeObject:
      name: SomeObject #Intentionally invalid
      type: object #Intentionally Invalid
      properties:
        Id:
          type: string
          format: uuid
          example: "d2014f64-ffdf-487b-8d12-67a20976aca6"
```
In this example the `name` and `type` fields are not part of a [SchemaObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject) and so the validator should logically fail.

`components/schema` is expected to be  a: `Map[string, Schema Object | Reference Object]` (see [componentsObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#componentsObject).

In this scenario the validator fails with:

```
{
    "keyword": "required",
    "dataPath": "/components/schemas/SomeObject",
    "schemaPath": "#/required",
    "params": {
      "missingProperty": "$ref"
    },
    "message": "should have required property '$ref'"
...
```

This is misleading because SomeObject should not have a property $ref; instead, the $ref in `components/schema` pointed to an invalid schema.

### Proposed solution:

A better message should either be:

> Object at /components/schemas/SomeObject is not a valid schemaObject

or

> `$ref: 'resources/myobject.yml#/resource/SomeObject'` points to an invalid schema object, schema object expected.

... or some variant.
